### ISSUE TITLE
No way to save html log and report

### ISSUE THREAD

**Issue by andyjmc** [datakurre/robotkernel#12]
It would be very useful to have an export to save the log and report files. Is there a way to do this?

**Comment by andyjmc** [comment]
I wrote a little function to do this `def javascript_export(html, filename):
    if isinstance(html, str):
        html = html.encode('utf-8')
    value =  (
        "javascript:(function(){{"
        "var w=window.open();"
        "var e = w.document.createElement('a');"
        "e.setAttribute('href', 'data:text/plain;charset=utf-8,' + atob('{}'));"
        "e.setAttribute('download', '{}');"
        "e.style.display = 'none';"
        "w.document.body.appendChild(e);"
        "e.click();"
        "document.body.removeChild(e);"
        "}})();".format(base64.b64encode(html).decode('utf-8'),filename)
    )
    return value`

**Comment by datakurre** [comment]
@andyjmc What is your use case for the export? Recent robotkernel versions install “nbrobot” script that is “robot” with support for ipynbfiles.

That said, I assume that “Jypyter” way would be to make robotkernel extend “nbconvert” with log export powers... but naming all those files would be an issue.

And, of course, that link with download attribute sounds also nice. I’ll think of it could be done by default without duplicating the data (that could be huge).

**Comment by andyjmc** [comment]
@datakurre Basically I want a clickable link beside the Log | Report links which I can use to not only view the results but download them as html files.

**Comment by datakurre** [comment]
@andyjmc I looked into this now and I will implement this so that Log or Report must be first opened in another tab and then at the top right corner there is a visible download-attribute based Download-link.

That seemed to be the only way to have the contents of those files only once in saved notebook files.

Most obvious way, of course, would have been just to generate another link next to Log and Report links with download data, but that would have duplicated the data. Dynamical approaches failed, because they did not work on JupyterLab.

**Comment by datakurre** [comment]
This was implemented in https://github.com/datakurre/robotkernel/pull/14/commits/e4324c9cf3a5fe7a78a89cfe3dd3df0f74521f9b

**Comment by datakurre** [comment]
Released in 0.9.0.
