### ISSUE TITLE
Log and report links do not work on JupyterLab

### ISSUE THREAD

**Issue by datakurre** [datakurre/robotkernel#6]
* [x] instead of "Log | Report" links "undefined" is rendered
* [x] links on existing notebooks are broken

**Comment by bollwyvl** [comment]
A simple link with embedded javascript works in a python notebook:
![screenshot from 2018-09-23 10-51-26](https://user-images.githubusercontent.com/45380/45929371-a13f3b80-bf1e-11e8-8c2e-9ea4bba8637e.png)

So I can't tell why you're seeing `undefined`... my closed one still draws does the thing, and isn't much more complex... however, I think this is probably a bug in JupyterLab, which is by design a lot more restrictive around techniques like this.

Stepping back a bit, in the work/beta testing I've been doing, I have come around to the thinking that proper lab integration with will have to be done in-DOM at the XML level, with custom mime renderers for:
- output.xml
- libdoc output (including the _almost_ markdown)

It represents more work than i can throw at it right now, since the existing stuff does _work_, but being able to inspect the output keywords, make it visually integrated with the rest of the experience, etc. is worth a lot. 

For dead-pixel HTML output from `jupyter nbconvert --execute`, it should still be possible to opt into capturing the full HTML logs...

**Comment by datakurre** [comment]
@bollwyvl I didn't do any changes to that code, so my "undefined" might be result of using the latest available jupyterlab. I need to try previous versions...

Custom renderer for output.xml sound cool, but it may not fully replace the current implementation that allows to distribute readable execution logs with rendered notebook files.

How do you handle failing test suites with ``jupyter nbconvert --execute``? Something better than ``--ExecutePreprocessor.allow_errors=True ``? (I'm also looking forward for https://github.com/jupyter/nbconvert/issues/626)

**Comment by bollwyvl** [comment]
> I didn't do any changes to that code, so my "undefined" might be result of using the latest available jupyterlab. I need to try previous versions...

Yeah, would have to do some more digging...

> How do you handle failing test suites with

I've been concentrating on the live editing state in JupyterLab, so I haven't done a bunch of work on the output end, yet. I'd probably overload `ExecutePreprocessor` with some different modes... 

```py
# jupyter_nbconvert_config.py
c.RobotPreprocessor.failure_behavior = 'fail_first' # | 'continue_and_exit_0` | 'continue_and_exit_1'
```

> Custom renderer for output.xml sound cool, but it may not fully replace the current implementation that allows to distribute readable execution logs with rendered notebook files.

Probably expose a setting that decided what type you'd want to export. Indeed, you can do crazy things like embedding the renderer (once) as inline javascript in the HTML, and have it turn `<script type='application/robot-output+xml></script>` into the rendered thing... not entirely dissimilar to how the report jquery stuff works... but probably wouldn't reuse it.

```py
# jupyter_nbconvert_config.py
c.RobotPreprocessor.embed_log_and_report_html = None # | 'window_open' | 'iframe' | 'js_renderer'
```
Advantage to having the thing itself embedded is that it could be `rebot`ed...

**Comment by bollwyvl** [comment]
I also updated with latest lab, and didn't see the condition... hm....

**Comment by datakurre** [comment]
Resolved this.

Rendering 'undefined' is a bug in Jupyter Lab caused by my code sending updates as `text/plain` at first, but `text/html` at the end. I fixed this by only sending with `text/html`.

https://github.com/datakurre/robotkernel/commit/3da7fce886bed8e3b902c21cf4bd555e42989755

"Broken links" on existing documents was just me forgetting that javascript-link require trusting the notebook.

**Comment by datakurre** [comment]
Related Jupyter Lab issue https://github.com/jupyterlab/jupyterlab/issues/5368#issuecomment-424225950
